syntax = "proto2";
package hw.trezor.messages.mintlayer;

import "messages-mintlayer-enums.proto";

// Sugar for easier handling in Java
option java_package = "com.satoshilabs.trezor.lib.protobuf";
option java_outer_classname = "TrezorMessageMintlayer";

/**
* Chain Type used to determine the coin name and bech32 prefixes
*/
enum MintlayerChainType {
    Mainnet = 1;
    Testnet = 2;
    Regtest = 3;
    Signet = 4;
}

/**
 * Request: Ask the device for the info about the current firmware
 * @start
 * @next MintlayerFirmwareInfo
 * @next Failure
 */
message MintlayerGetFirmwareInfo {}

/**
 * Response: The info about the current firmware
 * @end
 */
message MintlayerFirmwareInfo {
    required uint32 major_version = 1;          // major version of the firmware, e.g. 1
    required uint32 minor_version = 2;          // minor version of the firmware, e.g. 0
    required uint32 patch_version = 3;          // patch version of the firmware, e.g. 0
    required string prerelease_id = 4;          // semver pre-release identifier, e.g. "alpha"; can be empty
    required string build_metadata = 5;         // semver build metadata; can be empty
}

/**
 * Request: Ask the device for a Mintlayer address.
 * @start
 * @next MintlayerAddress
 * @next Failure
 */
message MintlayerGetAddress {
    repeated uint32 address_n = 1;               // BIP-32-style path to derive the key from master node
    required MintlayerChainType chain_type = 2;  // Chain type to use
    optional bool show_display = 3;              // optionally prompt for confirmation on trezor display
    optional bool chunkify = 4;                  // display the address in chunks of 4 characters
}

/**
 * Response: A Mintlayer address.
 * @end
 */
message MintlayerAddress {
    required string address = 1;    // prefixed bech32 Mintlayer address
}

/**
 * Request: Ask device for a public key corresponding to address_n path.
 * @start
 * @next MintlayerPublicKey
 */
message MintlayerGetPublicKey {
    repeated uint32 address_n = 1;               // BIP-32 path to derive the key from master node
    required MintlayerChainType chain_type = 2;  // Chain type to use
    optional bool show_display = 3;              // optionally prompt for confirmation on trezor display
}

/**
 * Response: A public key corresponding to address_n path.
 * @end
 */
message MintlayerPublicKey {
    required bytes public_key = 1;
    required bytes chain_code = 2;
}

/**
* Type of information required by transaction signing process
*/
enum MintlayerAddressType {
    PUBLIC_KEY = 1;
    PUBLIC_KEY_HASH = 2;
}

/**
 * Request: Ask device to sign a message
 * @start
 * @next Success
 * @next Failure
 */
message MintlayerSignMessage {
    repeated uint32 address_n = 1;                     // BIP-32 path to derive the key from master node
    required MintlayerChainType chain_type = 2;        // Chain type to use
    required MintlayerAddressType address_type = 3;    // Address type to use when signing the message Public key or Public key hash
    required bytes message = 4;                        // message to sign
}

/**
 * Request: Ask device to sign transaction
 * @start
 * @next MintlayerTxRequest
 * @next Failure
 */
message MintlayerSignTx {
    required uint32 outputs_count = 1;                         // number of transaction outputs
    required uint32 inputs_count = 2;                          // number of transaction inputs
    required MintlayerChainType chain_type = 3;                // Chain type to use
    required uint32 input_commitments_version = 4;             // input commitments version
    optional uint32 version = 5 [default=1];                   // transaction version
    optional bool chunkify = 6;                                // display addresses in chunks of 4 characters
}

/**
 * Response: Device asks for information for signing transaction or returns the last result
 * If input_request or output_request is set, device awaits MintlayerTxAck matching the request type.
 * @end
 * @next MintlayerTxAck
 */
message MintlayerTxRequest {
    optional MintlayerTxInputRequest input_request = 1;                // request for additional data for an input
    optional MintlayerTxOutputRequest output_request = 2;              // request for additional data for an output
    optional MintlayerTxSigningResult signing_finished = 3;            // serialized data containing the signatures

    /**
    * Request for additional data for a tx input
    */
    message MintlayerTxInputRequest {
        required uint32 input_index = 1;                      // index for the requested input
    }

    /**
    * Request for additional data for a tx output
    */
    message MintlayerTxOutputRequest {
        required uint32 output_index = 1;                     // index for the requested output
        optional bytes tx_hash = 2;                           // transaction hash for the specified output or none for the current transaction that is being signed
    }
    /**
    * Structure representing a single signature
    */
    message MintlayerSignature {
        required bytes signature = 1;             // a single signature
        optional uint32 multisig_idx = 2;         // in case of multisig the index of the key
    }
    /**
    * Structure representing all of the signatures for a single input, can be multiple for a multisig address
    */
    message MintlayerSignaturesForInput {
        required uint32 input_index = 1;                      // 'signatures' field contains signed input of this index
        repeated MintlayerSignature signatures = 2;           // all signatures for an input
    }
    /**
    * Structure representing serialized data
    */
    message MintlayerTxSigningResult {
        repeated MintlayerSignaturesForInput signatures = 1;  // signatures for all signed inputs
        // TODO: add serialized transaction
    }
}

/** Data type for an address
 * @embed
 */
message MintlayerAddressPath {
    repeated uint32 address_n = 1;                                      // BIP-32 path to derive the key from master node
    optional uint32 multisig_idx = 2;                                   // in case of a multisig the key index
}

/** Data type for the transaction's UTXO input.
 *
 * @embed
 */
message MintlayerUtxoTxInput {
    repeated MintlayerAddressPath addresses = 1;                        // 0 or more addresses for which the corresponding private keys will be used to sign the transaction
    required bytes prev_hash = 2;                                       // hash of previous transaction output to spend by this input
    required uint32 prev_index = 3;                                     // index of previous output to spend
    required enums.MintlayerUtxoType type = 4;                          // source type of the utxo (Transaction or BlockReward)
}

/** Data type for the transaction's Account input.
 *
 * @embed
 */
message MintlayerAccountTxInput {
    repeated MintlayerAddressPath addresses = 1;                                // 0 or more addresses for which the corresponding private keys will be used to sign the transaction
    required uint64 nonce = 2;                                                  // incremental account nonce
    optional MintlayerAccountSpendingDelegationBalance delegation_balance = 3;  // spend from a delegation balance
}

/** Data type for account spending from a delegation balance
 * @embed
 */
message MintlayerAccountSpendingDelegationBalance {
    required string delegation_id = 1;             // the delegation id of the account in bech32 encoding
    required bytes amount = 2;                     // amount to spend (in atoms as big-endian u128)
}

/** Data type for the transaction's AccountCommand input.
 *
 * @embed
 */
message MintlayerAccountCommandTxInput {
    repeated MintlayerAddressPath addresses = 1;                             // 0 or more addresses for which the corresponding private keys will be used to sign the transaction
    required uint64 nonce = 2;                                               // incremental account nonce
    optional MintlayerMintTokens mint = 3;                                   // mint tokens
    optional MintlayerUnmintTokens unmint = 4;                               // unmint tokens
    optional MintlayerLockTokenSupply lock_token_supply = 5;                 // lock token supply
    optional MintlayerFreezeToken freeze_token = 6;                          // freeze token
    optional MintlayerUnfreezeToken unfreeze_token = 7;                      // unfreeze token
    optional MintlayerChangeTokenAuthority change_token_authority = 8;       // change token authority
    optional MintlayerConcludeOrder conclude_order = 9;                      // conclude an order
    optional MintlayerFillOrder fill_order = 10;                             // fill an order
    optional MintlayerChangeTokenMetadataUri change_token_metadata_uri = 11; // change token metadata uri
}

/** Data type for the transaction's OrderAccountCommand input.
 *
 * @embed
 */
message MintlayerOrderCommandTxInput {
    repeated MintlayerAddressPath addresses = 1;                             // 0 or more addresses for which the corresponding private keys will be used to sign the transaction
    optional MintlayerFillOrderV1 fill = 2;                                  // fill order
    optional MintlayerFreezeOrder freeze = 3;                                // freeze order
    optional MintlayerConcludeOrderV1 conclude = 4;                          // conclude order
}

/** Data type for the order command FillOrder (V1)
 * @embed
 */
message MintlayerFillOrderV1 {
    required string order_id = 1;                        // order id in bech32 encoding
    required bytes amount = 2;                           // amount of the 'ask' currency (in atoms as big-endian u128)
    required MintlayerOutputValue initially_asked = 3;   // the initial ask balance of the order
    required MintlayerOutputValue initially_given = 4;   // the initial give balance of the order
}

/** Data type for the order command FreezeOrder
 * @embed
 */
message MintlayerFreezeOrder {
    required string order_id = 1;                        // order id in bech32 encoding
}

/** Data type for the order command ConcludeOrder (V1)
 * @embed
 */
message MintlayerConcludeOrderV1 {
    required string order_id = 1;                        // order id in bech32 encoding
    required MintlayerOutputValue initially_asked = 2;   // the initial ask balance of the order
    required MintlayerOutputValue initially_given = 3;   // the initial give balance of the order
    required bytes ask_balance = 4;                      // the remaining ask balance of the order
    required bytes give_balance = 5;                     // the remaining give balance of the order
}

/** Data type for the account command MintTokens
 * @embed
 */
message MintlayerMintTokens {
    required string token_id = 1;                  // token id in bech32 encoding
    required bytes amount = 2;                     // amount of tokens to mint (in atoms as big-endian u128)
}

/** Data type for the account command UnmintTokens
 * @embed
 */
message MintlayerUnmintTokens {
    required string token_id = 1;                  // token id in bech32 encoding
}

/** Data type for the account command LockTokenSupply
 * @embed
 */
message MintlayerLockTokenSupply {
    required string token_id = 1;                  // token id in bech32 encoding
}

/** Data type for the account command FreezeToken
 * @embed
 */
message MintlayerFreezeToken {
    required string token_id = 1;                  // token id in bech32 encoding
    required bool is_token_unfreezable = 2;        // is unfreezable after freezing it
}

/** Data type for the account command UnfreezeToken
 * @embed
 */
message MintlayerUnfreezeToken {
    required string token_id = 1;                  // token id in bech32 encoding
}

/** Data type for the account command ChangeTokenAuthority
 * @embed
 */
message MintlayerChangeTokenAuthority {
    required string token_id = 1;                  // token id in bech32 encoding
    required string destination = 2;               // destination for the new authority in bech32 encoding
}

/** Data type for the account command ConcludeOrder (V0)
 * @embed
 */
message MintlayerConcludeOrder {
    required string order_id = 1;                        // order id in bech32 encoding
    required MintlayerOutputValue initially_asked = 2;   // the initial ask balance of the order
    required MintlayerOutputValue initially_given = 3;   // the initial give balance of the order
    required bytes ask_balance = 4;                      // the remaining ask balance of the order (in atoms as big-endian u128)
    required bytes give_balance = 5;                     // the remaining give balance of the order (in atoms as big-endian u128)
}

/** Data type for the account command FillOrder (V0)
 * @embed
 */
message MintlayerFillOrder {
    required string order_id = 1;                        // order id in bech32 encoding
    required bytes amount = 2;                           // amount of the 'ask' currency (in atoms as big-endian u128)
    required string destination = 3;                     // the destination in bech32 encoding
    required MintlayerOutputValue initially_asked = 4;   // the initial ask balance of the order
    required MintlayerOutputValue initially_given = 5;   // the initial give balance of the order
    required bytes ask_balance = 6;                      // the remaining ask balance of the order (in atoms as big-endian u128)
    required bytes give_balance = 7;                     // the remaining give balance of the order (in atoms as big-endian u128)
}

/** Data type for the account command ChangeTokenMetadataUri
 * @embed
 */
message MintlayerChangeTokenMetadataUri {
    required string token_id = 1;                  // token id in bech32 encoding
    required bytes metadata_uri = 2;               // new metadata uri
}

/** Data type for the information about the token inside MintlayerOutputValue
 * @embed
 */
message MintlayerTokenOutputValue {
    required string token_id = 1;                  // token id in bech32 encoding

    // Note: in the end these values are passed to `format_coin_amount_int` in `core/src/apps/mintlayer/sign_tx/layout.py`,
    // where they are currently ignored.
    // TODO: token info handling has to be revamped, see https://github.com/mintlayer/mintlayer-trezor-firmware/issues/6
    required bytes token_ticker = 2;               // the token ticker
    required uint32 number_of_decimals = 3;        // the number of decimals for the token
}

/** Data type for an output value, which can be either coins or tokens
 * @embed
 */
message MintlayerOutputValue {
    required bytes amount = 1;                     // the amount (in atoms as big-endian u128)
    optional MintlayerTokenOutputValue token = 2;  // the token info or none if the value is in coins
}

/** Data type for the transaction's Transfer output.
 * @embed
 */
message MintlayerTransferTxOutput {
    required string address = 1;                    // destination address in bech32 encoding
    required MintlayerOutputValue value = 2;        // the output value to transfer
}

/** Data type for the time lock of an output
 * @embed
 */
message MintlayerOutputTimeLock {
    optional uint64 until_height = 1;                    // lock until block height
    optional uint64 until_time = 2;                      // lock until time
    optional uint64 for_block_count = 3;                 // lock for number of blocks
    optional uint64 for_seconds = 4;                     // lock for number of seconds
}

/** Data type for the transaction's LockThenTransfer output.
 * @embed
 */
message MintlayerLockThenTransferTxOutput {
    required string address = 1;                    // destination address in bech32 encoding
    required MintlayerOutputValue value = 2;        // the output value to transfer
    required MintlayerOutputTimeLock lock = 3;      // output lock
}

/** Data type for the transaction's Burn output.
 * @embed
 */
message MintlayerBurnTxOutput {
    required MintlayerOutputValue value = 1;        // the output value to burn
}

/** Data type for the transaction's CreateStakePool output.
 * @embed
 */
message MintlayerCreateStakePoolTxOutput {
    required string pool_id = 1;                   // the pool id in bech32 encoding
    required bytes pledge = 2;                     // the pledge amount (in atoms as big-endian u128)
    required string staker = 3;                    // the staker destination address in bech32 encoding
    required string vrf_public_key = 4;            // the VRF public key address in bech32 encoding
    required string decommission_key = 5;          // the decommission key in bech32 encoding
    required uint32 margin_ratio_per_thousand = 6; // the margin ratio per thousand
    required bytes cost_per_block = 7;             // the cost per block
}

/** Data type for the transaction's ProduceBlockFromStake output.
 * @embed
 */
message MintlayerProduceBlockFromStakeTxOutput {
    required string destination = 1;              // the staker destination address in bech32 encoding
    required string pool_id = 2;                  // the pool id in bech32 encoding
    required bytes staker_balance = 3;            // the current staker balance of the pool
}

/** Data type for the transaction's CreateDelegationId output.
 * @embed
 */
message MintlayerCreateDelegationIdTxOutput {
    required string destination = 1;              // the delegation owner destination address in bech32 encoding
    required string pool_id = 2;                  // the pool id in bech32 encoding
}

/** Data type for the transaction's DelegateStaking output.
 * @embed
 */
message MintlayerDelegateStakingTxOutput {
    required bytes amount = 1;               // the amount to delegate (in atoms as big-endian u128)
    required string delegation_id = 2;       // the delegation id in bech32 encoding
}

/** Data type for the token's total supply
 * @embed
 */
message MintlayerTokenTotalSupply {
    required enums.MintlayerTokenTotalSupplyType type = 1;  // the type of total token supply
    optional bytes fixed_amount = 2;                        // optional amount in case of fixed total token supply (in atoms as big-endian u128)
}

/** Data type for the transaction's IssueFungibleToken output.
 * @embed
 */
message MintlayerIssueFungibleTokenTxOutput {
    required bytes token_ticker = 1;                             // the token ticker
    required uint32 number_of_decimals = 2;                      // the number of decimals for the token
    required bytes metadata_uri = 3;                             // the metadata uri
    required MintlayerTokenTotalSupply total_supply = 4;         // the total supply limit
    required string authority = 5;                               // the token authority destination address in bech32 encoding
    required bool is_freezable = 6;                              // if the token freezable or not
}

/** Data type for the transaction's IssueNft output.
 * @embed
 */
message MintlayerIssueNftTxOutput {
    required string token_id = 1;                                // the token id in bech32 encoding
    required string destination = 2;                             // the NFT authority destination address in bech32 encoding
    optional string creator = 3;                                 // the NFT creator destination address in bech32 encoding (pub key address only)
    required bytes name = 4;                                     // the NFT name
    required bytes description = 5;                              // the NFT description
    required bytes ticker = 6;                                   // the NFT ticker
    optional bytes icon_uri = 7;                                 // the NFT icon uri
    optional bytes additional_metadata_uri = 8;                  // the NFT additional metadata uri
    optional bytes media_uri = 9;                                // the NFT media uri
    required bytes media_hash = 10;                              // the NFT media hash
}

/** Data type for the transaction's DataDeposit output.
 * @embed
 */
message MintlayerDataDepositTxOutput {
    required bytes data = 1;    // the data to be deposited
}

/** Data type for the transaction's HTLC output.
 * @embed
 */
message MintlayerHtlcTxOutput {
    required MintlayerOutputValue value = 1;                   // the output value to transfer
    required bytes secret_hash = 2;                            // the hash of the exchanged secret
    required string spend_key = 3;                             // the key that can spend the HTLC given the secret in bech32 encoding
    required MintlayerOutputTimeLock refund_timelock = 4;      // refund time lock
    required string refund_key = 5;                            // the key for a refund after the time lock has expired in bech32 encoding
}

/** Data type for the transaction's CreateOrder output.
 * @embed
 */
message MintlayerCreateOrderTxOutput {
    required string conclude_key = 1;                          // The key that can authorize conclusion of the order in bech32 encoding
    required MintlayerOutputValue ask = 2;                     // ask value of the order for coin or token
    required MintlayerOutputValue give = 3;                    // give value of the order for coin or token
}

/**
 * Request: Data about input or output, sent in response to MintlayerTxRequest
 *
 * @next MintlayerTxRequest
 */
message MintlayerTxAck {
    optional MintlayerTxInput input = 1;   // Ack response for an input
    optional MintlayerTxOutput output = 2; // Ack response for an output

    /**
     * Request: Data about input.
     *
     * @next MintlayerTxRequest
     */
    message MintlayerTxInput {
        optional MintlayerUtxoTxInput utxo = 1;                       // UTXO input
        optional MintlayerAccountTxInput account = 2;                 // account spending input
        optional MintlayerAccountCommandTxInput account_command = 3;  // account command input
        optional MintlayerOrderCommandTxInput order_command = 4;      // order account command input
    }

    /**
     * Request: Data about output.
     *
     * @next MintlayerTxRequest
     */
    message MintlayerTxOutput {
        optional MintlayerTransferTxOutput transfer = 1;                                 // transfer output
        optional MintlayerLockThenTransferTxOutput lock_then_transfer = 2;               // lock then transfer output
        optional MintlayerBurnTxOutput burn = 3;                                         // burn output
        optional MintlayerCreateStakePoolTxOutput create_stake_pool = 4;                 // create stake pool output
        optional MintlayerProduceBlockFromStakeTxOutput produce_block_from_stake = 5;    // create block from stake output
        optional MintlayerCreateDelegationIdTxOutput create_delegation_id = 6;           // create delegation Id output
        optional MintlayerDelegateStakingTxOutput delegate_staking = 7;                  // delegate staking output
        optional MintlayerIssueFungibleTokenTxOutput issue_fungible_token = 8;           // issue fungible token output
        optional MintlayerIssueNftTxOutput issue_nft = 9;                                // issue NFT output
        optional MintlayerDataDepositTxOutput data_deposit = 10;                         // data deposit output
        optional MintlayerHtlcTxOutput htlc = 11;                                        // HTLC output
        optional MintlayerCreateOrderTxOutput create_order = 12;                         // Create order output
    }
}
